### ISSUE TITLE
Example Contract to write EIP712 credentials on chain

### ISSUE THREAD

**Issue by digitalmnt** [gitcoinco/eas-proxy#32]
After the migration to compose db all VCs will be signed with an EIP712 signature type. This ticket is meant to create a solidity smart contract that verifies stamps EIP712 signed stamps

**Comment by digitalmnt** [comment]
I was able to track do

Looking at https://github.com/spruceid/ssi/blob/db906df40b24836f62a087b2e57f2d9b26a19ed8/ssi-ldp/src/eip712.rs#L1514 it doesn't look like it is possible to generate the Domain Seperator without providing types to the issue_credential method.

**Comment by nutrina** [comment]
I have created this script https://github.com/nutrina/passport-vc-verification/blob/test_eip712/utils/didkitVerify.ts
that should verify the validity of a credential with ethers.

This works for credentials generated using: https://github.com/nutrina/passport-vc-verification/blob/test_eip712/utils/didkitSign.ts

But this does not work for credentials generated with Passport (When run on my local).

**Comment by nutrina** [comment]
We have limited ourselves to validating the credentials with ethers, will create a SC for validation at a later point
